baseURL = "https://cupppa.github.io/"
theme = "cupper"
title = "cupppa"

#enableRobotsTXT = true
#enableEmoji = true
enableGitInfo = true

defaultContentLanguage = "en"           # Default language to use
languageCode = "en-us"

#hasCJKLanguage = true     # has chinese/japanese/korean ? # 自动检测是否包含 中文\日文\韩文
#paginate = 10                                             # 首页每页显示的文章数
#rssLimit = 20             # Limit Entry Count to Rss file # 限制 Rss 文章输出数量

disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = "cupppa"            # default: author.name ↓        # 默认为下面配置的author.name ↓
# uglyURLs = true         # more info: https://gohugo.io/content-management/urls/#ugly-urls

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename"

[imaging]
  quality = 99

[[menu.nav]]             # config your menu              # 配置目录
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Blog"
  weight = 20
  identifier = "blog"
  url = "/post/"
[[menu.nav]]
  name = "Tags"
  weight = 30
  identifier = "/tags/"
  url = "/tags/"
[[menu.nav]]
  name = "RSS"
  weight = 50
  identifier = "rss"
  url = "/index.xml"
[[menu.nav]]
  name = "About"
  weight = 60
  url = "/about/"
[[menu.nav]]
  name = "hugo"
  weight = 100
  url = "https://gohugo.io"


[params]
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  # uglyURLs = true          # You must set true after use uglyURLs in site (above). because $.Site.UglyURLs can not import.
  since = "2018"            # Site creation time          # 站点建立时间
  homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  homeMetaContent = "An accessibility-friendly Hugo theme, ported from the original Cupper project."
  footer = "Make with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [github.io](https://github.io/)."
  dateFormat = "2006-01-02 15:04"
  codePenUser = ""
  katex = true
  darkThemeAsDefault = false
  search = true
  # A list of custom css files can be provided, which must be placed inside 'static/'.
  # This is useful to override just specific css classes, instead of copying the entire
  # theme's css file to your own site.
  # Usage:
  # customCss:
  #   - css/foo.css # relative path starting from static/
  # - css/bar.css
  
[markup]
  defaultMarkdownHandler = "goldmark"
[markup.goldmark.extensions]
  definitionList = true
  footnote = true
  linkify = true
  strikethrough = true
  table = true
  taskList = true
  typographer = true
[markup.goldmark.parser]
  attribute = true
  autoHeadingID = true
[markup.goldmark.renderer]
  hardWraps = false
  unsafe = true
  xHTML = false
[markup.heiglight]
  codeFences = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4
[markup.tableOfContents]
  endLevel = 6
  startLevel =2